[package]
name = "fib2"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
p3-air = { path = "../air" }
p3-goldilocks = { path = "../goldilocks" }
p3-challenger = { path = "../challenger" }
p3-commit = { path = "../commit" }
p3-dft = { path = "../dft", features = ["parallel"] }
p3-field = { path = "../field" }
p3-fri = { path = "../fri" }
p3-interpolation = { path = "../interpolation" }
p3-keccak = { path = "../keccak" }
p3-matrix = { path = "../matrix" }
p3-merkle-tree = { path = "../merkle-tree" }
p3-poseidon2 = { path = "../poseidon2" }
p3-blake3 = { path = "../blake3" }
p3-symmetric = { path = "../symmetric" }
p3-uni-stark = { path = "../uni-stark", features = ["parallel"] }
p3-util = { path = "../util", features = ["parallel"] }


atty.workspace = true
rand.workspace = true
rayon.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

ark-std = { version = "0.5", features = ["print-trace"] }

# Trace convertor and Miden VM dependencies
p3-trace-convertor = { path = "../trace-convertor" }



miden-assembly = { path = "../../miden-vm/assembly", default-features = false }
miden-processor = { path = "../../miden-vm/processor", default-features = false }
miden-prover = { path = "../../miden-vm/prover", default-features = false, features = ["std"] }
miden-verifier = { path = "../../miden-vm/verifier", default-features = false }
miden-vm = { path = "../../miden-vm/miden-vm", default-features = false, features = [ "executable" ] }
winter-prover = { version = "0.13", default-features = false, features = ["std", "concurrent"]  }

# [patch.crates-io]
# winter-air = { path = "../../winterfell/air", default-features = false }
# winter-crypto = { path = "../../winterfell/crypto" }
# winter-fri = { path = "../../winterfell/fri" }
# winter-math = { path = "../../winterfell/math", default-features = false }
# winter-prover = { path = "../../winterfell/prover", default-features = false, features = ["std"] }
# winter-rand-utils = { path = "../../winterfell/utils/rand" }
# winter-utils = { path = "../../winterfell/utils/core", default-features = false }
# winter-verifier = { path = "../../winterfell/verifier", default-features = false }
